/**
 * @file RandomKmeans.cuh
 * @brief Random hierarchical data generator with a KMeans-compatible interface.
 *
 * @details RandomKmeans generates a synthetic multi-level dataset entirely on
 * the host without performing any real clustering.  It is used by
 * IndexBuilder::buildRandom() to produce an IndexData in seconds regardless
 * of the requested size, enabling rapid testing of the query pipeline.
 *
 * Generation strategy (coarse-to-fine):
 *   1. The coarsest layer is generated first: N_coarsest points drawn
 *      uniformly from [valMin, valMax]^D.
 *   2. Each subsequent finer layer is generated by scattering
 *      `ratio` child points around every point of the coarser layer.
 *      Child points are drawn from a Gaussian centred on their parent
 *      with standard deviation sigma = clusterRadius (computed from the
 *      global value range and the number of clusters at that level),
 *      then clamped to [valMin, valMax].
 *   3. All layers are stored during construction.
 *
 * The interface mirrors CUDAKmeans / CPUKmeans exactly so that
 * IndexBuilder::runBuild can use any of the three backends without
 * modification.  Because the hierarchy is pre-built, run() is O(1).
 *
 * Iteration order:
 *   IndexBuilder drives the loop from fine to coarse, calling reset()
 *   between levels.  RandomKmeans inverts this: it stores layers ordered
 *   fine-to-coarse and advances a cursor toward coarser layers on each
 *   reset() call.
 */

#pragma once

#include <algorithm>
#include <cassert>
#include <cmath>
#include <cstddef>
#include <random>
#include <stdexcept>
#include <vector>

/**
 * @class RandomKmeans
 * @brief Synthetic KMeans-compatible data generator for rapid index testing.
 *
 * @details Generates a complete coarse-to-fine hierarchy of random data
 * during construction so that each run() call simply reads precomputed
 * results.  All values are within [valMin, valMax] and are optionally
 * rounded to integers.
 *
 * Typical usage inside IndexBuilder::runBuild (unchanged from real KMeans):
 * @code
 *   RandomKmeans kmeans(N, D, ratios, valMin, valMax, isInt);
 *   for each level:
 *       kmeans.run(k, ...);     // reads precomputed layer
 *       // use getdatas(), getCentroids(), getLabels()
 *       kmeans.reset();         // advance to next (coarser) layer
 * @endcode
 */
class RandomKmeans {
public:
    using Point = std::vector<double>;

    /*!
     * @brief Pre-generate the full coarse-to-fine hierarchy.
     *
     * @details Builds all layers during construction so that run() is O(1).
     * The number of layers equals ratios.size() + 1 (one extra for the
     * coarsest mesh that IndexBuilder reads via getCentroids() on the last
     * iteration).
     *
     * @param[in] N       Number of points at the finest layer.
     * @param[in] D       Dimensionality of each point.
     * @param[in] ratios  Coarsening ratios (finest-to-coarsest order, same
     *                    vector passed to IndexBuilder::build).
     * @param[in] valMin  Lower bound of the value range (must be > 0).
     * @param[in] valMax  Upper bound of the value range.
     * @param[in] isInt   When true, all coordinates are rounded to the
     *                    nearest integer.
     * @throws std::invalid_argument When valMin <= 0 or valMin >= valMax.
     */
    RandomKmeans(size_t N, size_t D, const std::vector<size_t>& ratios, double valMin, double valMax,
                 bool isInt)
        : D_(D), isInt_(isInt), valMin_(valMin), valMax_(valMax), cursor_(0) {
        if (valMin <= 0.0)
            throw std::invalid_argument("RandomKmeans: valMin must be > 0");
        if (valMin >= valMax)
            throw std::invalid_argument("RandomKmeans: valMin must be < valMax");

        generate(N, ratios);
        if (!layerPoints_.empty()) {
            datas_ = layerPoints_[0];
        }
    }

    /*!
     * @brief Read the precomputed clustering result for the current layer.
     *
     * @details Populates datas_, centroids_, and labels_ from the
     * pre-generated layers.  The cursor_ determines which layer pair is
     * used; reset() advances it.  k must equal the centroid count that
     * was computed during construction for this layer.
     *
     * @param[in] k         Expected number of centroids (checked by assert).
     * @param[in] max_iters Unused; present for interface compatibility.
     */
    void run(size_t k, size_t /*max_iters*/ = 100) {
        assert(cursor_ < layerPoints_.size());
        assert(cursor_ + 1 < layerPoints_.size());

        datas_      = layerPoints_[cursor_];
        centroids_  = layerPoints_[cursor_ + 1];
        labels_     = layerLabels_[cursor_];

        assert(centroids_.size() == k);
        if (centroids_.size() != k) {
            throw std::runtime_error("RandomKmeans::run: centroid count mismatch");
        }
    }

    /*!
     * @brief Advance the cursor to the next (coarser) layer.
     *
     * @details After reset(), the next run() call will provide data for
     * the coarser adjacent layer pair.
     */
    void reset() {
        ++cursor_;
        assert(cursor_ < layerPoints_.size());
        datas_ = layerPoints_[cursor_];
        centroids_.clear();
        labels_.clear();
    }

    [[nodiscard]] const std::vector<size_t>& getLabels()    const { return labels_; }    /*!< Per-point parent index. */
    [[nodiscard]] const std::vector<Point>&  getCentroids() const { return centroids_; } /*!< Parent layer points. */
    [[nodiscard]] const std::vector<Point>&  getdatas()     const { return datas_; }     /*!< Current layer points. */
    [[nodiscard]] size_t get_curr_layer_length() const { return datas_.size(); }     /*!< Points in current layer. */
    [[nodiscard]] size_t get_next_layer_length() const { return centroids_.size(); } /*!< Points in parent layer. */

private:
    size_t D_;
    bool   isInt_;
    double valMin_;
    double valMax_;
    size_t cursor_;

    // layerPoints_[0] = finest, layerPoints_.back() = coarsest
    std::vector<std::vector<Point>>  layerPoints_;
    // layerLabels_[l][i] = index of the parent point in layerPoints_[l+1]
    //                       for point i in layerPoints_[l]
    std::vector<std::vector<size_t>> layerLabels_;

    // Active layer data (set by run())
    std::vector<Point>  datas_;
    std::vector<size_t> labels_;
    std::vector<Point>  centroids_;

    /*!
     * @brief Build all layers from coarsest to finest.
     *
     * @param[in] N      Target number of points at the finest layer.
     * @param[in] ratios Coarsening ratios in finest-to-coarsest order.
     */
    void generate(size_t N, const std::vector<size_t>& ratios) {
        std::mt19937_64 rng(12345);

        const size_t intervals = ratios.size();

        // Compute coarsest layer size by applying ratios in reverse
        // (coarsest = finest / product-of-ratios, clamped to >= 1)
        size_t coarsestN = N;
        for (size_t r : ratios) {
            coarsestN = std::max(size_t(1), coarsestN / r);
        }

        // layerSizes[0] = finest, layerSizes[intervals] = coarsest
        std::vector<size_t> layerSizes(intervals + 1);
        layerSizes[0] = N;
        {
            size_t cur = N;
            for (size_t i = 0; i < intervals; ++i) {
                cur = std::max(size_t(1), cur / ratios[i]);
                layerSizes[i + 1] = cur;
            }
        }

        // Allocate storage (coarsest first in layerPoints_ index = intervals,
        // finest = 0; we fill coarse-to-fine then reverse at the end)
        layerPoints_.resize(intervals + 1);
        layerLabels_.resize(intervals); // labels_[l] maps fine[l] -> coarse[l+1]

        // Generate coarsest layer uniformly in [valMin, valMax]^D
        std::uniform_real_distribution<double> uniDist(valMin_, valMax_);
        layerPoints_[intervals].resize(coarsestN);
        for (size_t i = 0; i < coarsestN; ++i) {
            layerPoints_[intervals][i].resize(D_);
            for (size_t d = 0; d < D_; ++d) {
                layerPoints_[intervals][i][d] = roundIfNeeded(uniDist(rng));
            }
        }

        // Generate each finer layer from the one above (coarse-to-fine)
        // layer index in layerPoints_: coarsest = intervals, finest = 0
        for (size_t lvl = intervals; lvl > 0; --lvl) {
            // parent layer = lvl, child layer = lvl - 1
            const auto& parents = layerPoints_[lvl];
            const size_t nParents = parents.size();
            const size_t nChildren = layerSizes[lvl - 1];

            // Cluster radius: spread children within a fraction of the
            // average inter-parent spacing, estimated as:
            //   (valMax - valMin) / nParents^(1/D) / 3
            const double spacing =
                (valMax_ - valMin_) / std::pow(static_cast<double>(nParents), 1.0 / static_cast<double>(D_));
            const double sigma = spacing / 3.0;

            std::normal_distribution<double> normDist(0.0, sigma);

            auto& children = layerPoints_[lvl - 1];
            auto& labels   = layerLabels_[lvl - 1];
            children.resize(nChildren);
            labels.resize(nChildren);

            // Distribute children round-robin across parents, then add noise
            for (size_t ci = 0; ci < nChildren; ++ci) {
                const size_t parentIdx = ci % nParents;
                labels[ci] = parentIdx;
                children[ci].resize(D_);
                const auto& parent = parents[parentIdx];
                for (size_t d = 0; d < D_; ++d) {
                    double val = parent[d] + normDist(rng);
                    val = std::clamp(val, valMin_, valMax_);
                    children[ci][d] = roundIfNeeded(val);
                }
            }
        }
        // layerPoints_[0] is now the finest layer, ready to use.
    }

    double roundIfNeeded(double v) const {
        return isInt_ ? std::round(v) : v;
    }
};
